version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-api01
    ports:
      - "4001:4001"
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: mysql:8.0.33
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: vm50
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
volumes:
  mysql-data:
    driver: local