version '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    depends_on:
      - db
  db:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: 'jL9@xZ2!tQ6*kT1)>D5+nA^|lN4~zF5$'
      MYSQL_DATABASE: vm50
    volumes:
      - ./data:/var/lib/mysql